try 
{
    Write-Output
} 
catch 
{
    Write-Output "Something threw an exception"
    Write-Output $_
}